### ISSUE TITLE
update rest api please

### ISSUE THREAD

**Issue by Yuri-Neko** [Chandra-XD/ItsukaChan#11]

**Comment by Chandra-XD** [comment]
nggak ada hostingan cuy

**Comment by Yuri-Neko** [comment]
> nggak ada hostingan cuy

🗿aws free tier ada... heroku

**Comment by Tjandraaaa** [comment]
malas ah, gw pake hasil skrep
walaupun nggak banyak

**Comment by Yuri-Neko** [comment]
> malas ah, gw pake hasil skrep walaupun nggak banyak

lalu bot ga update lagi nih mas

**Comment by Tjandraaaa** [comment]
yg error ma bagian downloader doang si keknya
sama yg anime" itu, kapan" dah gw samain kek bot pribadi gw

**Comment by Yuri-Neko** [comment]
> yg error ma bagian downloader doang si keknya sama yg anime" itu, kapan" dah gw samain kek bot pribadi gw

gw make ini cuma isi plugins di ganti biar bisa sendlist message :v
